name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: create     
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}\build      
      run: cmake ..
    - name: make
      working-directory: ${{github.workspace}}\build
      shell: bash
      run: cmake --build .
